name: Convert Text to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install LaTeX
      run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex

    - name: Convert student file to PDF
      run: pandoc student/student_document.txt --pdf-engine=xelatex -o student.pdf

    - name: Convert sat file to PDF
      run: pandoc sat/sat_document.txt --pdf-engine=xelatex -o sat.pdf

    - name: Upload PDFs
      uses: actions/upload-artifact@v2
      with:
        name: pdf-documents
        path: |
          student.pdf
          sat.pdf
