name: Convert Text to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install pdflatex
      run: sudo apt-get install -y texlive-latex-base

    - name: Convert text file to PDF
      run: pandoc MANUAL.txt -o output.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: pdf-document
        path: output.pdf
